CC = gcc

APP = cli

SOURCE_DIR = $(PWD)
ROOT_DIR = $(SOURCE_DIR)/../..
BUILD_DIR = $(SOURCE_DIR)/../build

SRCS = $(SOURCE_DIR)/*.c

CFLAGS = -g

ALL : compile_check compile

clean : clean_build

include $(ROOT_DIR)/env.mk
